"use strict";
exports.__esModule = true;
var professional_1 = require("./professional");
var professional1 = new professional_1.Professional("PepitoPalote", 65, "Male", 71, 189, "Castaño", "Azul", "Caucasico", true, "Irlandés", 58, "Actor");
var professional2 = new professional_1.Professional("Paquita La del Barrio", 75, "Female", 82, 159, "Rubio", "Avellana", "Caucasico", true, "Mexicana", 0, "Cantante");
var professional3 = new professional_1.Professional("Clint Eastwood", 91, "Male", 80, 190, "Gris", "Azul", "Caucasico", false, "Estado Unidense", 2, "Actor, Director");
var professional4 = new professional_1.Professional("Donnie Yen", 58, "Male", 68, 173, "Negro", "Negro", "Asiático", false, "Chino", 0, "Actor, Director, Productor");
professional1.consolePrint();
professional2.consolePrint();
professional3.consolePrint();
professional4.consolePrint();
